version: '3.1'

services:
  backend:
    image: 

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dira_is_the_best
      POSTGRES_DB: dira
    ports:
      - 5432:5432
